hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra           # Store hydra's config breakdown here for debugging
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://navsim.planning.script.config.common 

defaults:
  - _self_
  - default_common
  - default_evaluation
  - default_scoring_parameters
  - agent: constant_velocity_agent

# Use NAVSIM_EXP_ROOT if provided, otherwise fallback to $HOME/.goalflow
metric_cache_path: ${oc.env:NAVSIM_EXP_ROOT,${oc.env:HOME}/.goalflow}/metric_cache # path to metric cache
dac_label_path: null